### ISSUE TITLE
exec format error

### ISSUE THREAD

**Issue by asdfok** [EvilFreelancer/docker-routeros#11]
Hi, I'm trying to install this on raspberry pi 4. When I checked the log on the portainer, it's giving me this.
exec user process caused: exec format error
how to fix this?

**Comment by EvilFreelancer** [comment]
Hello! This is not possible for right now, because image based on alpine for amd64. But you may create yet another version of Dockerfile with arm cpu support.

PS. Sorry for long response, i've forgot answer to you in May.
