### ISSUE TITLE
Error when run Cannot find device "qemubr1"

### ISSUE THREAD

**Issue by robiokidenis** [EvilFreelancer/docker-routeros#13]
i have error when running this image on my docker vps, this is details

Cannot find device "qemubr1"
udhcpd: started, v1.31.1
udhcpd: max_leases=235 is too big, setting to 1
udhcpd: can't open '/var/lib/udhcpd/udhcpd.leases': No such file or directory
udhcpd: ioctl 0x8933 failed: No such device
qemu-system-x86_64: could not open /dev/net/tun: No such file or directory

**Comment by EvilFreelancer** [comment]
Hello! Which version of Docker do you have?

docker -v

It should be at least 20.x

**Comment by robiokidenis** [comment]
i use latest version, 
Docker version 20.10.8 running on ubuntu  20.04.3

**Comment by iserbkin** [comment]
Hello!
Same here on two different systems: Ubuntu 21.04 and Docker Desktop for Windows 10
