### ISSUE TITLE
very nice job ,why do not update to hub.docker.com?

### ISSUE THREAD

**Issue by lanyucomputer** [EvilFreelancer/docker-routeros#14]
very nice job ,why do not update to hub.docker.com? it is only for arm64?

**Comment by lanyucomputer** [comment]
standard_init_linux.go:207: exec user process caused "exec format error"

**Comment by EvilFreelancer** [comment]
> why do not update to hub.docker.com?

Hello! Yeah, some time ago on Docker Hub was autobuilds for an OpenSource projects, but then they rejected this feature and i have no time for switching to GitHub Actions for example.

> it is only for arm64?
> standard_init_linux.go:207: exec user process caused "exec format error"

This image is x86/64 only, not possible to run on ARM yet, i just have no time to implement this, sorry.

**Comment by EvilFreelancer** [comment]
I would be very happy if you help implement automatic build and publish on Docker Hub via GitHub Actions.

https://github.com/nektos/act for tests

**Comment by lanyucomputer** [comment]
> Hello! Yeah, some time ago on Docker Hub was autobuilds for an OpenSource projects, but then they rejected this feature and i have no time for switching to GitHub Actions for example.
> 
> >https://hub.docker.com/r/mkv28/mikrotik-routeros  this is for ARM
