### ISSUE TITLE
How to run in host mode?

### ISSUE THREAD

**Issue by lls2wow** [EvilFreelancer/docker-routeros#16]
Hi I use this command run :
```
docker run --cap-add=NET_ADMIN --device=/dev/net/tun --network host -ti evilfreelancer/docker-routeros
```

It start ok but can`t connected with winbox and mikrotik self can`t ping the gateway

**Comment by wgcontrol** [comment]
answer please

**Comment by EvilFreelancer** [comment]
Hi! This is not possible, because RouterOS is running inside QEMU virtual machine inside a container.

But you may use network_mode: host and your QEMU VM will have direct access to host network, this mean you will need to change settings in entrypoint.sh manually.
