### ISSUE TITLE
There was an error running this Docker on the Alpine Linux system, please resolve the issue!

### ISSUE THREAD

**Issue by tony-2009** [EvilFreelancer/docker-routeros#44]
attached the log information:

Failed to send flush request: Operation not permitted
RTNETLINK answers: Operation not permitted
Error: argument "qemubr1" is wrong: Device does not exist

RTNETLINK answers: Operation not permitted
Cannot find device "qemubr1"
KVM not available, running in emulation mode. This will be slow.
udhcpd: started, v1.36.1
udhcpd: max_leases=235 is too big, setting to 1
udhcpd: can't open '/var/lib/udhcpd/udhcpd.leases': No such file or directory
udhcpd: ioctl 0x8933 failed: No such device
qemu-system-x86_64: -nic tap,id=qemu1,mac=54:05:AB:CD:12:31,script=/routeros/qemu-ifup,downscript=/routeros/qemu-ifdown: could not open /dev/net/tun: No such file or directory
🌏

**Comment by EvilFreelancer** [comment]
Hi! I don't think it is possible, AplineOS is a good OS for embedded devices or for docker images, but not for dedicated servers. The warnings that are visible in your logs indicate this, you need to configure BIOS of server (enable KVM) and fix some OS settings (configure /dev/net/tun) before trying to launch the container.

But you may try to run a VDI-image of RouterOS directly via QEMU without help of Docker Engine, details in [Dockerfile](https://github.com/EvilFreelancer/docker-routeros/blob/master/Dockerfile) and [entrypoint.sh](https://github.com/EvilFreelancer/docker-routeros/blob/master/scripts/entrypoint.sh).
