### ISSUE TITLE
db failure: database or disk is full:stoppped

### ISSUE THREAD

**Issue by offlinejke** [EvilFreelancer/docker-routeros#6]
Hello my friend. 
I use this image as a server for the Dude. Today I encountered such a problem while trying connect to server.
I freed up a couple megabytes of space on routeros but still can't connect to the dude. How can fix it? May be is it possible to create a volume for a specific folder, or what may be the options?

**Comment by EvilFreelancer** [comment]
Hello @offlinejke !

As you probably know the RouterOS is not support dockerization process, so i've used VDI image in combination with qemu virtual machine.

https://github.com/EvilFreelancer/docker-routeros/blob/master/scripts/entrypoint.sh

That mean if you see "not enough space" error then space is ended inside VDI image.

I can suggest to look at [this article](http://derekmolloy.ie/resize-a-virtualbox-disk/#:~:text=Go%20into%20%E2%80%9COracle%20VM%20VirtualBox,now%20almost%20out%20of%20space!) and resize the VDI of your RouterOS.

Another idea is to make automatic resizing of the disk at the time of assembly of the docker container.

**Comment by EvilFreelancer** [comment]
Yet another article which may be helpful:

https://askubuntu.com/questions/280849/mount-bind-with-full-ownership-and-permissions

You can `mount --bind` any folder from your root system inside docker container, but for this will need update entrypoint.sh scripts with required parameters.

**Comment by offlinejke** [comment]
Thank you for your suggest. I will try this articles.

**Comment by EvilFreelancer** [comment]
This topic about sharing host filesystem in qemu

https://cialu.net/qemu-kvm-on-ubuntu-and-sharing-files-between-host-and-guests/

I think better way is
1) create docker-compose with volume which is some folder on your host machine and mountpiint inside container is some folder like /share
2) update entrypont.sh, need to add binding from `/share` of container to somewhere in virtual machine
3) restart composition with new sttings

For right now i don't know how exactly (only in general) make this but hope you can find the answer and explain to me :)

**Comment by offlinejke** [comment]
Just got to the case. So i added vdi file to vmware, expand disk to the required size and add it into the volume. Restarted container and that is all.
Thanks for the help)
